name: Build on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Zaktualizowana wersja

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Zaktualizowana wersja
        with:
          node-version: '20'  # Aktualizacja do Node.js 20

      - name: Change directory to project folder
        run: cd 'NEXTPBX BOT'

      - name: Install dependencies
        run: npm install
        working-directory: 'NEXTPBX BOT'  # Ustawienie katalogu roboczego

      - name: Build the project
        run: npm run build-mac  # Upewnij się, że masz odpowiedni skrypt w package.json
        working-directory: 'NEXTPBX BOT'  # Ustawienie katalogu roboczego

      - name: Run tests
        run: npm test
        working-directory: 'NEXTPBX BOT'  # Ustawienie katalogu roboczego
